version: '3.7'

services:
  openldap:
    image: bitnami/openldap:2
    container_name: openldap
    hostname: openldap
    ports:
      - 1389:1389
      - 1636:1636
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: adminpassword
      LDAP_ROOT: dc=example,dc=org
    volumes:
      - ./openldap_data:/bitnami/openldap
      - ./ldifs:/ldifs
  webapp:
    build: .
    depends_on:
      - openldap
    links:
      - openldap:openldap
    ports:
      - 8080:8080
    environment:
      # from .env file
      OKTA_URL: ${OKTA_URL}
      OKTA_LDAP_ID: ${OKTA_LDAP_ID}
      OKTA_LDAP_HOST: ${OKTA_LDAP_HOST}
      OKTA_LDAP_BASE: ${OKTA_LDAP_BASE}
      OKTA_LDAP_USERNAME: ${OKTA_LDAP_USERNAME}
      OKTA_LDAP_PASSWORD: ${OKTA_LDAP_PASSWORD}
  agent:
    build: okta-ldap-agent
    container_name: ldap-agent
    hostname: ldap-agent
    depends_on:
      - openldap
    links:
      - openldap:openldap
    environment:
      # from .env file
      OKTA_URL: ${OKTA_URL}
      LDAP_HOST: openldap
      LDAP_PORT: 1389
      LDAP_ROOT: dc=example,dc=org
      LDAP_ADMIN_USERNAME: cn=admin,dc=example,dc=org
      LDAP_ADMIN_PASSWORD: adminpassword
    volumes:
      - ./okta-ldap-agent/conf:/opt/Okta/OktaLDAPAgent/conf