version: '3.7'

services:
  openldap:
    image: bitnami/openldap:2
    container_name: openldap
    hostname: openldap
    ports:
      - 1389:1389
      - 1636:1636
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: adminpassword
      LDAP_ROOT: dc=example,dc=org
    volumes:
      - ./openldap_data:/bitnami/openldap
      - ./ldifs:/ldifs
  webapp:
    build: .
    ports:
      - 8080:8080
    environment:
      # from .env file
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OKTA_ISSUER_URI: ${ISSUER}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OKTA_CLIENT_ID: ${CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OKTA_CLIENT_SECRET: ${CLIENT_SECRET}
  agent:
    build: okta-ldap-agent
    container_name: ldap-agent
    hostname: ldap-agent
    depends_on:
      - openldap
    links:
      - openldap:openldap
    environment:
      # from .env file
      OKTA_URL: ${OKTA_URL}
      LDAP_HOST: openldap
      LDAP_PORT: 1389
      LDAP_ROOT: dc=example,dc=org
      LDAP_ADMIN_USERNAME: cn=admin,dc=example,dc=org
      LDAP_ADMIN_PASSWORD: adminpassword
    volumes:
      - ./okta-ldap-agent/conf:/opt/Okta/OktaLDAPAgent/conf